### ISSUE TITLE
Error encountered: name 'threading' is not defined

### ISSUE THREAD

**Issue by DenoGeek** [neveresthub/s3-python-backup-library#1]
**Describe the bug**
I tried executing the script with a specified directory but encountered the following error.
`^CTraceback (most recent call last):
  File "spaces.py", line 67, in upload_dir
    client.upload_file(filepath, bucket ,os.path.abspath(filepath) ,Callback=ProgressPercentage(filepath))
  File "/home/dev/bck/s3-python-backup-library/utils.py", line 9, in __init__
    self._lock = threading.Lock()
NameError: name 'threading' is not defined
`

**To Reproduce**
1.Install requirements
2. Attempt a backup

**Expected behavior**
Success messages on upload

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu server 18.04]

**Comment by mwikya** [comment]
issue fixed
